import Head from "next/head";
import Link from "next/link";
import { useRecoilState } from "recoil";
import {
  Box,
  Button,
  Container,
  Grid,
  GridItem,
  Heading,
  Text,
} from "@chakra-ui/react";

import { listsState } from "../src/hooks/listsState";

export default function Home() {
  const [lists, setLists] = useRecoilState(listsState);

  return (
    <Container
      h="100vh"
      position="relative"
      backgroundImage="linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)"
      maxW="auto"
    >
      <Head>
        <title>Rent Service App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        h={{ base: "auto", md: 600 }}
        my="6"
        boxShadow="lg"
        rounded="lg"
        w={{
          base: "calc(100% - 40px)",
          md: 1000,
        }}
        m="auto"
        p={8}
        background="#fff"
        position="absolute"
        top={{ base: 10, md: "50%" }}
        left="50%"
        transform={{
          base: "translate(-50%, 0)",
          md: "translate(-50%, -50%)",
        }}
      >
        <Heading as="h1" size="xl" mb={10} color="teal.400">
          Find a Flat.
        </Heading>

        <Link href="/create">
          <Button
            size="lg"
            w={200}
            borderRadius={20}
            bg={"teal.400"}
            colorScheme="teal"
            display="block"
            mx="auto"
            mb={10}
          >
            Add
          </Button>
        </Link>

        <Grid templateColumns="repeat(2,1fr)">
          {lists.map((list) => {
            return (
              <GridItem w="100%" key={list.id}>
                <Heading as="h2" size="md" mb={2} color="gray.500">
                  Address
                </Heading>
                <Text mb={8}>{list.address}</Text>
                <Heading as="h2" size="md" mb={2} color="gray.500">
                  Type
                </Heading>
                <Text mb={8}>{list.type}</Text>
                <Heading as="h2" size="md" mb={2} color="gray.500">
                  Description
                </Heading>
                <Text mb={10}>{list.description}</Text>
                <Link href={`/show/${list.id}`}>
                  <button>Detail</button>
                </Link>
              </GridItem>
            );
          })}
        </Grid>
      </Box>
    </Container>
  );
}
